"""user, entries and imgs

Revision ID: 2dfff6ba3dc7
Revises: 634dac682e28
Create Date: 2020-09-21 15:34:27.438706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2dfff6ba3dc7'
down_revision = '634dac682e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('imgs',
        sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column('img_1', mysql.MEDIUMBLOB(), nullable=False),
        sa.Column('img_2', mysql.MEDIUMBLOB(), nullable=True),
        sa.Column('img_3', mysql.MEDIUMBLOB(), nullable=True),
        sa.Column('img_4', mysql.MEDIUMBLOB(), nullable=True),
        sa.Column('filetypes_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    
    op.create_table('filetypes',
        sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column('ft_1', sa.String(length=5), nullable=False),
        sa.Column('ft_2', sa.String(length=5), nullable=True),
        sa.Column('ft_3', sa.String(length=5), nullable=True),
        sa.Column('ft_4', sa.String(length=5), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )


    op.add_column('entries', sa.Column('description', sa.LargeBinary(length=4294967295), nullable=True))
    op.add_column('entries', sa.Column('imgs_id', sa.Integer(), nullable=False))

    op.create_foreign_key(
        'fk_imgs_id',
        'entries', 'imgs',
        ['imgs_id'], ['id'], 
    )
    op.create_foreign_key(
        'fk_filetypes_id',
        'imgs', 'filetypes',
        ['filetypes_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'description')
    op.drop_table('imgs')
    ### end Alembic commands ###
