"""users and entries v 03 working

Revision ID: 634dac682e28
Revises: 16fd10f0eca3
Create Date: 2020-09-19 18:41:38.247203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '634dac682e28'
down_revision = '16fd10f0eca3'
branch_labels = None
depends_on = None

#First Version that works with SQLAlchemy :D

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    
    op.drop_index(op.f('ix_entries_created_at'), table_name='entries')
    
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.create_index('ix_user_username', 'users', ['username'], unique=True)
    op.create_index('ix_user_email', 'users', ['email'], unique=True)
    op.create_index('id', 'users', ['user_id'], unique=True)
    # ### end Alembic commands ###
