"""final

Revision ID: 647bcf5fd36c
Revises: c72755003741
Create Date: 2020-10-08 00:51:00.819491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '647bcf5fd36c'
down_revision = 'c72755003741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'description',
               existing_type=mysql.VARCHAR(length=240),
               nullable=True)
    op.alter_column('users', 'otp_secret',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'otp_secret',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('entries', 'description',
               existing_type=mysql.VARCHAR(length=240),
               nullable=False)
    # ### end Alembic commands ###
